# Generated by Django 4.1.4 on 2022-12-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characteristic',
            new_name='Trait',
        ),
    ]
