# Generated by Django 4.1.4 on 2022-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('traits', '0002_rename_characteristic_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='animal',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
